// Cloudflare API v4 over fetch. The token lives in secrets/cloudflare.ini and is
// the same one certbot uses. Permissions:
//   Zone → DNS → Edit                    certificates (DNS-01) and DNS records   (required)
//   Zone → SSL and Certificates → Edit   Cloudflare Origin CA certificates       (optional)

import fs from 'node:fs';
import { P } from './config.mjs';

const API = 'https://api.cloudflare.com/client/v4';

export class CloudflareError extends Error {}

async function api(token, method, route, body) {
  let res;
  try {
    res = await fetch(API + route, {
      method,
      headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: body ? JSON.stringify(body) : undefined,
      signal: AbortSignal.timeout(20_000),
    });
  } catch (err) {
    throw new CloudflareError(`could not reach Cloudflare: ${err.cause?.code || err.message}`);
  }
  const data = await res.json().catch(() => ({}));
  if (!res.ok || data.success === false) {
    const msg = (data.errors || []).map((e) => `${e.message}${e.code ? ` (${e.code})` : ''}`).join('; ');
    throw new CloudflareError(msg || `HTTP ${res.status}`);
  }
  return data.result;
}

export async function verifyToken(token) {
  const r = await api(token, 'GET', '/user/tokens/verify');
  if (r?.status !== 'active') throw new CloudflareError(`token is ${r?.status || 'not active'}`);
  return r;
}

/** The zone a hostname lives in (tries a.b.example.com → b.example.com → example.com). */
export async function findZone(token, host) {
  const labels = host.split('.');
  for (let i = 0; i < labels.length - 1; i++) {
    const name = labels.slice(i).join('.');
    const zones = await api(token, 'GET', `/zones?name=${encodeURIComponent(name)}`);
    if (zones?.length) return { id: zones[0].id, name: zones[0].name };
  }
  return null;
}

export async function getRecords(token, zoneId, name) {
  const all = await api(token, 'GET', `/zones/${zoneId}/dns_records?name=${encodeURIComponent(name)}&per_page=100`);
  return (all || []).filter((r) => ['A', 'AAAA', 'CNAME'].includes(r.type));
}

/**
 * Point `name` at `ip` (A record) with the proxy on or off.
 * Returns 'created' | 'updated' | 'unchanged'. Refuses to replace a CNAME.
 */
export async function upsertA(token, zoneId, name, ip, proxied) {
  const records = await getRecords(token, zoneId, name);
  const cname = records.find((r) => r.type === 'CNAME');
  if (cname) throw new CloudflareError(`${name} is a CNAME to ${cname.content} — change it in the dashboard`);
  const a = records.find((r) => r.type === 'A');
  const body = { type: 'A', name, content: ip, proxied, ttl: 1, comment: 'managed by nginx-edge' };
  if (!a) {
    await api(token, 'POST', `/zones/${zoneId}/dns_records`, body);
    return 'created';
  }
  if (a.content === ip && a.proxied === proxied) return 'unchanged';
  await api(token, 'PATCH', `/zones/${zoneId}/dns_records/${a.id}`, body);
  return 'updated';
}

export async function deleteRecords(token, zoneId, name) {
  const records = (await getRecords(token, zoneId, name)).filter((r) => r.type === 'A' || r.type === 'AAAA');
  for (const r of records) await api(token, 'DELETE', `/zones/${zoneId}/dns_records/${r.id}`);
  return records.length;
}

/** Sign a CSR with Cloudflare's Origin CA. Returns the certificate PEM. */
export async function createOriginCert(token, hostnames, csr) {
  const r = await api(token, 'POST', '/certificates', {
    hostnames,
    csr,
    request_type: 'origin-rsa',
    requested_validity: 5475,
  });
  if (!r?.certificate) throw new CloudflareError('Cloudflare returned no certificate');
  return r.certificate;
}

/** This server's public IPv4 as Cloudflare sees it. */
export async function publicIp() {
  try {
    const res = await fetch('https://1.1.1.1/cdn-cgi/trace', { signal: AbortSignal.timeout(8000) });
    const m = (await res.text()).match(/^ip=([0-9.]+)$/m);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

/** Refresh the real-IP ranges and the Authenticated Origin Pulls CA. */
export async function syncCloudflareFiles() {
  const get = async (url) => {
    const res = await fetch(url, { signal: AbortSignal.timeout(20_000) });
    if (!res.ok) throw new CloudflareError(`${url}: HTTP ${res.status}`);
    return res.text();
  };
  const [v4, v6] = await Promise.all([get('https://www.cloudflare.com/ips-v4'), get('https://www.cloudflare.com/ips-v6')]);
  const ranges = `${v4}\n${v6}`.split(/\s+/).filter((r) => r.includes('/'));
  if (ranges.length < 10) throw new CloudflareError('unexpected answer from cloudflare.com/ips');
  const date = new Date().toISOString().slice(0, 10);
  fs.writeFileSync(
    P.realip,
    `# Generated by edge cf-sync on ${date} — do not edit by hand.\n` +
      `# Restores the real visitor IP from Cloudflare's CF-Connecting-IP header.\n` +
      ranges.map((r) => `set_real_ip_from ${r};`).join('\n') +
      `\nreal_ip_header CF-Connecting-IP;\n`,
  );
  let aop = false;
  try {
    const ca = await get('https://developers.cloudflare.com/ssl/static/authenticated_origin_pull_ca.pem');
    if (ca.includes('BEGIN CERTIFICATE')) {
      fs.mkdirSync(PATH_DIR(P.aopCa), { recursive: true });
      fs.writeFileSync(P.aopCa, ca);
      aop = true;
    }
  } catch {
    /* only needed when AOP is switched on */
  }
  return { ranges: ranges.length, aop };
}

const PATH_DIR = (p) => p.slice(0, p.lastIndexOf('/'));
